# Application Configuration
spring.application.name=remote-it-support-server
server.port=8080
server.address=0.0.0.0

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3308/remote-it-support?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JWT CONFIGURATION
jwt.secret=CHANGE_ME_SUPER_SECRET_256_BITS_KEY
jwt.expiration=3600000
# HEARTBEAT CONFIGURATION
agent.heartbeat.timeout=30
agent.scheduler.rate=10000
